# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sz2x9ImUCHfZMYMgolIOZCn-G93ZBBJb
"""

import streamlit as st
import pandas as pd
import os

# Definir credenciales de inicio de sesión
usuario_correcto = "41640530"
contrasenia_correcta = "cayetano"

# Cargar logo de la universidad
logo = st.image("/content/cayetano.jpg", width=200)

# Formulario de inicio de sesión
st.sidebar.title("Iniciar Sesión")
usuario = st.sidebar.text_input("Usuario")
contrasenia = st.sidebar.text_input("Contraseña", type="password")

if usuario == usuario_correcto and contrasenia == contrasenia_correcta:
    st.success("¡Inicio de sesión exitoso!")

    # Bienvenidaa
    st.title("¡Bienvenido a tu Plan de Estudios durante el trayecto de tu vida Universitaria!")
    st.write("En esta sección podrás acceder a la información detallada de los cursos que forman parte de tu plan de estudios, desde el Primer Ciclo hasta el Décimo Ciclo.")

    # Cargar datos del plan de estudios
    plan_estudios = pd.read_csv("/content/database.csv")

    # Mostrar tabla con información de los cursos
    st.subheader("Cursos de tu Plan de Estudios")

    # Estilos CSS
    st.markdown("""
        <style>
        body {
            background-color: #F5F5F5; /* Gris claro */
            color: #333333; /* Gris oscuro */
            font-family: Arial, sans-serif;
        }
        .course-table {
            border-collapse: collapse;
            width: 100%;
            font-size: 14px;
        }
        .course-table th, .course-table td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        .course-table th {
            background-color: #f2f2f2;
        }
        .course-table tr:hover {
            background-color: #f5f5f5;
        }
        .course-table .prereq-cell {
            font-weight: bold;
        }
        </style>
    """, unsafe_allow_html=True)

    # Función para obtener el color de fondo según el ciclo
    def get_bg_color(ciclo, prereq):
        if prereq == "NINGUNO":
            return "#f2f2f2"  # Gris claro
        elif ciclo.startswith("PRIMER"):
            return "#e6f0ff"  # Azul claro
        elif ciclo.startswith("SEGUNDO"):
            return "#e6ffff"  # Turquesa claro
        elif ciclo.startswith("TERCER"):
            return "#fffce6"  # Amarillo claro
        elif ciclo.startswith("CUARTO"):
            return "#fef0e6"  # Lino
        elif ciclo.startswith("QUINTO"):
            return "#fff5ee"  # Seashell
        elif ciclo.startswith("SEXTO"):
            return "#f5f5dc"  # Beige
        elif ciclo.startswith("SEPTIMO"):
            return "#e6e6fa"  # Lavanda
        elif ciclo.startswith("OCTAVO"):
            return "#fff0f5"  # Lavanda rojizo
        elif ciclo.startswith("NOVENO"):
            return "#f8f8ff"  # Azul fantasma
        elif ciclo.startswith("DECIMO"):
            return "#f5deb3"  # Wheat
        else:
            return ""  # Sin color de fondo

    # Mostrar los cursos por ciclo
    for ciclo in plan_estudios["CICLO"].unique():
        cursos = plan_estudios[plan_estudios["CICLO"] == ciclo]
        st.subheader(f"{ciclo}")
        styled_cursos = cursos.style.apply(lambda value: [f"background-color: {get_bg_color(ciclo, value['PRE REQUISITO'])};color: black;"], axis=1, subset=["PRE REQUISITO"])
        styled_cursos = styled_cursos.set_table_styles([
            {"selector": "th", "props": [("background-color", "#f2f2f2"), ("font-weight", "bold")]},
            {"selector": "tr:hover", "props": [("background-color", "#f5f5f5")]}
        ])
        st.write(styled_cursos.to_html(classes="course-table"), unsafe_allow_html=True)

    st.write("Nota: Los cursos en color tienen prerrequisitos que deben ser aprobados antes de llevarlos.")

    # Mostrar video didáctico ;p
    st.subheader("Video Didáctico")
    video_url = "https://youtu.be/TV7Dj8lch4k?si=LtNi84VBxhBthH4P"
    st.video(video_url)

else:
    if st.sidebar.button("Iniciar Sesión"):
        st.error("Credenciales incorrectas. Por favor, inténtalo de nuevo.")