# -*- coding: utf-8 -*-
"""iniciar sesion. análisis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItbpgrV9lTfITVvxJ2pMUvuD2RzCKEw_
"""

pip install streamlit

import streamlit as st
import pandas as pd
# Cargar datos desde el archivo CSV
data = pd.read_csv("/content/database.csv")

# Configurar el diseño de la página
st.set_page_config(page_title="Gestión de Cursos UPCH", page_icon=":books:", layout="wide")

# Encabezado y descripción
st.markdown("""
<div style="background-color: #007bff; color: white; padding: 2rem; border-radius: 0.5rem;">
    <div style="display: flex; align-items: center;">
        <img src="/content/cayetano.png" alt="Logo" width="50" height="50" style="margin-right: 1rem;">
        <h1>Gestión de Cursos de Ingeniería Informática - UPCH</h1>
    </div>
    <p>Esta aplicación web permite visualizar los cursos de los 10 ciclos de la carrera de Ingeniería Informática en la Universidad Peruana Cayetano Heredia (UPCH), junto con sus prerrequisitos y detalles.</p>
</div>
""", unsafe_allow_html=True)

# Estilos CSS
hide_table_row_index = """
            <style>
            tbody th {display:none;}
            .blank {display:none;}
            </style>
            """
st.markdown(hide_table_row_index, unsafe_allow_html=True)

# Función para obtener el color de fondo según el ciclo
def get_bg_color(ciclo):
    colors = {
        "PRIMER": "#F0F8FF",  # Azul claro
        "SEGUNDO": "#E0FFFF",  # Turquesa claro
        "TERCER": "#FAFAD2",  # Amarillo claro
        "CUARTO": "#FAF0E6",  # Lino
        "QUINTO": "#FFF5EE",  # Seashell
        "SEXTO": "#F5F5DC",  # Beige
        "SEPTIMO": "#E6E6FA",  # Lavanda
        "OCTAVO": "#FFF0F5",  # Lavanda rojizo
        "NOVENO": "#F8F8FF",  # Azul fantasma
        "DECIMO": "#F5DEB3"  # Wheat
    }
    for key, value in colors.items():
        if ciclo.startswith(key):
            return value
    return ""  # Sin color de fondo

# Mostrar los cursos por ciclo
for ciclo in data["CICLO"].unique():
    cursos = data[data["CICLO"] == ciclo]
    st.markdown(f"""
    <div style="background-color: #f4f4f4; padding: 1rem; border-radius: 0.5rem; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
        <div style="display: flex; align-items: center; margin-bottom: 1rem;">
            <img src="/content/cayetano.png" alt="Logo" width="30" height="30" style="margin-right: 0.5rem;">
            <h2>{ciclo}</h2>
        </div>
        {cursos.style.apply(lambda x: [f"background-color: {get_bg_color(ciclo)}"] * len(x), axis=1).to_html(index=False)}
    </div>
    """, unsafe_allow_html=True)

# Nota al pie
st.write("Nota: Los cursos en color tienen prerrequisitos que deben ser aprobados antes de llevarlos.")

streamlit run app.py