# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sz2x9ImUCHfZMYMgolIOZCn-G93ZBBJb
"""

import streamlit as st
import pandas as pd
import os

# Definir credenciales de inicio de sesión
usuario_correcto = "41650931"
contrasenia_correcta = "cayetano"

# Cargar logo de la universidad
logo_path = "/content/cayetano.jpg"
if os.path.exists(logo_path):
    logo = st.image(logo_path, width=200)
else:
    st.error("No se encontró el archivo de logo de la universidad.")

# Formulario de inicio de sesión
st.set_page_config(page_title="Inicio de Sesión - UPCH", page_icon=":lock:")
st.markdown("""
<div style="background-color: #007bff; color: white; padding: 2rem; border-radius: 0.5rem;">
    <h1>Iniciar Sesión</h1>
    <p>Por favor, ingresa tus credenciales para acceder a la aplicación.</p>
</div>
""", unsafe_allow_html=True)

# Crear el formulario de inicio de sesión
with st.form(key="login_form"):
    usuario = st.text_input("Usuario")
    contrasenia = st.text_input("Contraseña", type="password")
    submit_button = st.form_submit_button("Iniciar Sesión")

if submit_button:
    if usuario == usuario_correcto and contrasenia == contrasenia_correcta:
        st.success("¡Inicio de sesión exitoso!")
    else:
        st.error("Usuario o contraseña incorrectos.")